
[local]
localhost

[mongodb]
localhost

[catalogue]
catalogue-dev.srikanthchalla.online

[redis]
localhost

[user]
user-dev.srikanthchalla.online

[cart]
cart-dev.srikanthchalla.online

[mysql]
localhost

[shipping]
shipping-dev.srikanthchalla.online

[rabbitmq]
localhost
[payment]
payment-dev.srikanthchalla.online

[frontend]
frontend-dev.srikanthchalla.online
